name: Generate Changelog
on:
  release:
    types: [published]
permissions:
  contents: write
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate Changelog
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Add changelog to release
        run: gh release edit ${{ github.event.release.tag_name }} -F CHANGELOG.md